#!/bin/bash
set -e

JAR_FILE=$(find . -maxdepth 1 -name "*.jar" | head -n 1)

if [ -z "$JAR_FILE" ]; then
  echo "No JAR file found!" >&2
  exit 1
fi

export TOKEN=$(cat "$COBOT_SECRET_TOKEN_FILE")

exec java -jar "$JAR_FILE" --config config.yml
